version: "3.5"
services:
  httpbin:
    build:
      context: "fixtures/httpbin"
    networks:
      testnet:
        aliases:
          - htb.testing.local
  lts:
    restart: on-failure
    command: "npm run test"
    build:
      context: "."
      dockerfile: "Dockerfile-lts"
    networks:
      testnet:
        aliases:
          - lts.node.local
networks:
  testnet:
    name: testnet
    internal: true
