version: 3.5
services:
  httpbin:
    build:
      context: "fixtures/httpbin"
    networks:
      testnet:
        - htb.testing.local
  lts:
    restart: on-failure
    command: "npm run test"
    build:
      dockerfile: "Dockerfile-lts"
    networks:
      testnet:
        - lts.node.local
networks:
  testnet:
    internal: true
