jobs:
  build:
    docker:
      - image: cimg/node:16.2.0
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install
      - run:
          name: run test
          command: npm run test
      - run:
          name: uploade coverage to codecov
          command: |
            bash <(curl -s https://codecov.io/bash) 
