jobs:
  build:
    docker:
      - image: cimg/node:16.2.0
    resource_class: small
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install && npm install --save-dev
      - run:
          name: build
          command: npm run build
      - run:
          name: run test
          command: npm run test
      - run:
          - store_artifacts:
              path: coverage
      - run:
          name: merge coverage files for codecov
          command: bash -c "for i in ./coverage/{clover.xml,lcov-report}; do cat $i >> covarage.txt ; echo '<<<<<< EOF' >> coverage.txt; done"
      - run:
          name: remove original coverage files
          command: bash -c "rm -rv ./coverage"
      - run:
          name: uploade coverage to codecov
          command: npx codecov