jobs:
  build:
    docker:
      - image: cimg/node:16.2.0
    resource_class: small
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install && npm install --save-dev
      - run:
          name: build
          command: npm run build
      - run:
          name: run test
          command: npm run test
      - run:
          name: uploade coverage to codecov
          command: |
            npx jest --ci --coverage --forceExit && npx codecov