version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.5
  node: circleci/node@4.5.0

jobs:
  build:
    executor: 
      name: node/default

    steps:
      - checkout

      - run:
          name: install dependencies
          command: npm install && npm install --save-dev
      - run:
          name: build
          command: npm run build
      - run:
          name: run test
          command: npm run test
      - store_artifacts:
          path: coverage
      - coveralls/upload:
          flag_name: main
          verbose: true
      - run:
          name: uploade coverage to codecov
          command: bash <(curl -s https://codecov.io/bash) -v

workflows:
  build-and-report:
    jobs: 
      - build